#!/usr/bin/env python3
"""Normalize consumer-app research exports into a Round 1 workspace.

Example:
  python scripts/import_reports.py --topic "T" --scope "S" --output-dir research/t/round1 \
    --report academic=gemini:path/to/gemini.md \
    --report real-time=perplexity:path/to/perplexity.md \
    --report contrarian=chatgpt:path/to/chatgpt.md
"""

import argparse
import json
import shutil
import time
from pathlib import Path

VALID_ROLES = {"academic", "practitioner", "real-time", "grey-literature", "contrarian"}


def parse_report(value: str):
    try:
        head, path = value.split(":", 1)
        agent, provider = head.split("=", 1)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("use ROLE=PROVIDER:PATH") from exc
    if agent not in VALID_ROLES:
        raise argparse.ArgumentTypeError(f"unknown role '{agent}'")
    if not provider.strip() or not path.strip():
        raise argparse.ArgumentTypeError("provider and path cannot be blank")
    return agent, provider.strip(), Path(path)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--topic", required=True)
    ap.add_argument("--scope", required=True)
    ap.add_argument("--output-dir", required=True)
    ap.add_argument("--report", action="append", required=True, type=parse_report,
                    help="ROLE=PROVIDER:PATH; repeat for each export")
    args = ap.parse_args()

    seen = set()
    output = Path(args.output_dir)
    output.mkdir(parents=True, exist_ok=True)
    assignments = {}
    results = []
    for role, provider, source in args.report:
        if role in seen:
            raise SystemExit(f"duplicate role: {role}")
        seen.add(role)
        if not source.is_file():
            raise SystemExit(f"report not found: {source}")
        dest = output / f"agent-{role}.md"
        shutil.copyfile(source, dest)
        assignments[role] = provider
        results.append({"agent_type": role, "provider": provider, "model": "consumer-app-export",
                        "status": "ok", "words": len(dest.read_text(encoding="utf-8").split()),
                        "file": str(dest), "source_file": str(source)})

    manifest = {
        "topic": args.topic,
        "scope": args.scope,
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "source_mode": "consumer-app-import",
        "assignments": assignments,
        "strategy_count": len(assignments),
        "provider_count": len(set(assignments.values())),
        "results": results,
        "warnings": ["Imported reports were not generated by the API dispatcher; preserve source exports."],
    }
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"Imported {len(results)} reports from {manifest['provider_count']} providers into {output}")


if __name__ == "__main__":
    main()
